### ISSUE TITLE
添加了JMUIMultiSelectPhotosKit后，export archive出错

### ISSUE THREAD

**Issue by philying** [jpush/jmessage-ios-uikit#2]
添加了JMUIMultiSelectPhotosKit后，export archive出错，把JMUIMultiSelectPhotosKitResource.bundle删除后可以正常export，但选择图片会报错

![error](https://cloud.githubusercontent.com/assets/534031/20245079/1cb0d660-a9d3-11e6-922e-ebffeed0d50a.png)

**Comment by huangminlinux** [comment]
把   显示bundle 包内容   把里面的二进制文件删除，，  或者直接使用 工程中的 JMUIMultiSelectPhotosKitResource.bundle 文件，不要使用product 生成的bundle文件
